version: '3.8'

services:
  docker-updater:
    build: .
    container_name: lottery-docker-updater
    ports:
      - "3000:3000"
    volumes:
      # For Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # For Podman (uncomment if using Podman)
      # - /run/podman/podman.sock:/var/run/docker.sock:Z
    environment:
      - DOCKER_IMAGES=lottery-nginx,lottery-dotnet
      # Optional: Specify Docker host if managing remote Docker engine
      # Examples:
      #   - DOCKER_HOST=http://192.168.1.100:2375  (remote Docker daemon)
      #   - DOCKER_HOST=unix:///var/run/docker.sock (local socket)
      # - DOCKER_HOST=http://your-unraid-ip:2375
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
