name: Release - Build and Tag Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_number=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release image
        uses: docker/build-push-action@v5
        with:
          attest: false
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/lottery-docker-updater:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/lottery-docker-updater:${{ steps.version.outputs.version_number }}
            ghcr.io/${{ github.repository_owner }}/lottery-docker-updater:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.title=Lottery Docker Updater
            org.opencontainers.image.description=Next.js application for updating Docker containers
            org.opencontainers.image.version=${{ steps.version.outputs.version_number }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Docker Image
            ```bash
            docker pull ghcr.io/${{ github.repository_owner }}/lottery-docker-updater:${{ steps.version.outputs.version_number }}
            ```

            ## What's Changed
            See the full changelog in the commit history.

            ## Deployment
            For Unraid deployment instructions, see the [README.md](https://github.com/${{ github.repository }}/blob/main/README.md).
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "### Release ${{ steps.version.outputs.version }} Published! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Docker Images:**" >> $GITHUB_STEP_SUMMARY
          echo "- \`ghcr.io/${{ github.repository_owner }}/lottery-docker-updater:${{ steps.version.outputs.version_number }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`ghcr.io/${{ github.repository_owner }}/lottery-docker-updater:latest\`" >> $GITHUB_STEP_SUMMARY
